### PR TITLE
feat: navbar component

### PR DESCRIPTION
**Pull request by hetd54**

### CODE REVIEW

**Comment by AD121390** [comment]
Looks great!!

**Review by T0ny-X — APPROVED** [review]
Great beginning, appears to be waiting on the fireAuth logic (Shouldn't be a my profile when not logged in) and search bar to be complete.

**Review by AD121390 — APPROVED** [review]

**Review by hjones123 — APPROVED** [review]
Little late but agree with Tony and Adriel. Looks great and neat! No issues with loading the website.

**Comment by T0ny-X** [comment]
CSS Break Points are not suited for half desktop page

**Review by AD121390 — COMMENTED** [review]
Looks great!

**Review by hjones123 — APPROVED** [review]

**Pull request merged**
