### PR TITLE
Feat form

### PR DESCRIPTION
**Pull request by hetd54**
Visual of the two forms back-to-back:

https://github.com/CS633SP23Team4/magic-kitchen/assets/35639529/3b75b215-ca2e-414a-bb36-797fa6f34bca

Editing of the Avatar is not included right now, since we will need to implement storage first.

### CODE REVIEW

**Comment by T0ny-X** [comment]
Lovely, I would personally move the button to be down below the field instead of next to the title. Otherwise looks good.
image

**Review by AD121390 — COMMENTED** [review]
Looks great. I like the layout and the way components were designed. It looks super user friendly since they can just click and not have to type out the whole thing.

**Review by hjones123 — COMMENTED** [review]
The URL is not working for me, but I agree with Adriel and Tony that I enjoy the layout that you went with here Heather.

**Comment by hjones123** [comment]
Can discuss in 2/11/24 meeting, but would this section of submitting a recipe under the user profile page be a substitute to the "Submit a Recipe" page on the nav bar? In other words do we even need a submit a recipe page or will it all fall under the user profile.

**Review by AD121390 — APPROVED** [review]

**Pull request merged**
