### PR TITLE
Feat faq component

### PR DESCRIPTION
**Pull request by hetd54**
Here is a video of the functionality of the FAQ:

https://github.com/CS633SP23Team4/magic-kitchen/assets/35639529/02589b28-9364-44ee-b36b-adf298126b74

### CODE REVIEW

**Comment by T0ny-X** [comment]
Online Demo appears to not working yet

**Comment by T0ny-X** [comment]
@ah0606 
image
Is this expected or maybe we should just use 1 per row.

**Review by hjones123 — APPROVED** [review]
Looks good! I think for the purpose of the project, I think this fits what we are trying to accomplish with the FAQ section.

**Review by AD121390 — APPROVED** [review]
Awesome, I like the collapsible aspect of it, so that it doesn't look too busy.

**Pull request merged**
